import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2 } from 'lucide-react';
import { solidPrinciples, toLldSlug } from '@/lib/low-level-design';

export function generateStaticParams() { return solidPrinciples.map((item) => ({ slug: toLldSlug(item.name) })); }

export default async function SolidBlogPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const item = solidPrinciples.find((principle) => toLldSlug(principle.name) === slug);
  if (!item) notFound();
  const situation = item.name.startsWith('S') ? 'A service mixes pricing, persistence, emails, and reporting.' : item.name.startsWith('O') ? 'A checkout team keeps editing the same large switch statement every time a payment method is added.' : item.name.startsWith('L') ? 'A subtype passes compilation but changes the behavior callers rely on.' : item.name.startsWith('I') ? 'A small client is forced to implement methods it never uses.' : 'A business service directly constructs a vendor SDK and is impossible to test in isolation.';
  return <main className="min-h-screen px-6 py-8"><div className="mx-auto max-w-4xl space-y-6"><Header label="SOLID blog" /><article className="glass rounded-3xl p-6 md:p-10"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-cyan/15 text-cyan"><BookOpen /></div><p className="mt-6 text-sm font-semibold uppercase tracking-[0.25em] text-cyan">{item.short}</p><h1 className="mt-2 text-4xl font-black text-white md:text-6xl">{item.name}</h1><p className="mt-5 text-lg leading-8 text-slate-300">{item.explanation}</p><Section title="A real-world situation"><p>{situation}</p><p className="mt-3">The design smell is not simply “too many lines”. It is that a change in one business concern forces unrelated code to change, making reviews, tests, and deployments risky.</p></Section><Section title="How to apply it"><ul className="space-y-3"><Bullet>Find the reason the code changes and name that responsibility.</Bullet><Bullet>Extract a small interface or service around the policy.</Bullet><Bullet>Inject the abstraction into the use case and test it with a fake.</Bullet><Bullet>Keep the principle practical; do not create an interface for every class.</Bullet></ul></Section><Section title="Concrete example"><p className="text-violet-100"><strong>{item.example}</strong></p><pre className="mt-4 overflow-x-auto rounded-2xl border border-white/10 bg-black/30 p-4 font-mono text-xs leading-6 text-slate-200">interface PaymentGateway {'{'} charge(amount: number): Promise&lt;void&gt; {'}'}
class Checkout {'{'} constructor(private payment: PaymentGateway) {'}'}</pre></Section><Section title="Interview answer"><p>State the change pressure, show the bad coupling, draw the extracted relationship, then mention the trade-off: more objects and indirection in exchange for safer change and tests.</p></Section><Link href="/low-level-design" className="mt-6 inline-flex items-center gap-2 text-cyan">Back to LLD toolkit <ArrowRight className="h-4 w-4" /></Link></article></div></main>;
}
function Header({ label }: { label: string }) { return <nav className="flex items-center justify-between"><div className="text-sm font-bold text-white">SystemDesign Lab · {label}</div><Link href="/low-level-design" className="inline-flex items-center gap-2 rounded-2xl border border-white/15 px-3 py-2 text-sm text-slate-200"><ArrowLeft className="h-4 w-4" /> LLD</Link></nav>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-8 border-t border-white/10 pt-6"><h2 className="text-2xl font-black text-white">{title}</h2><div className="mt-3 text-sm leading-7 text-slate-300">{children}</div></section>; }
function Bullet({ children }: { children: React.ReactNode }) { return <li className="flex gap-2"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-emerald-300" />{children}</li>; }
