import Link from 'next/link';
import { ArrowLeft, ArrowRight, BookOpen, Boxes, Code2, Layers3 } from 'lucide-react';
import { AuthControls } from '@/features/auth/AuthControls';
import { designPatterns, lldTopics, solidPrinciples, toLldSlug, solidExamples, patternExamples } from '@/lib/low-level-design';
import { practiceProblems } from '@/lib/practice-problems';

export default function LowLevelDesignPage() {
  const problems = practiceProblems.filter((problem) => problem.category === 'Low-Level Design');
  return (
    <main className="min-h-screen px-6 py-8">
      <div className="mx-auto max-w-7xl space-y-10">
        <nav className="flex flex-col gap-4 rounded-3xl border border-white/10 bg-panel/70 p-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-brand shadow-glow"><Boxes className="h-5 w-5" /></div><div><div className="font-bold text-white">SystemDesign Lab</div><div className="text-xs text-slate-400">Track 2 · Low-Level Design</div></div></div>
          <div className="flex items-center gap-3"><AuthControls /><Link href="/" className="inline-flex items-center gap-2 rounded-2xl border border-white/15 px-3 py-2 text-sm text-slate-200 hover:bg-white/10"><ArrowLeft className="h-4 w-4" /> Home</Link></div>
        </nav>
        <section className="grid gap-8 lg:grid-cols-[1.1fr_0.9fr] lg:items-center">
          <div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-violet-300/30 bg-violet-400/10 px-3 py-1 text-sm text-violet-100"><BookOpen className="h-4 w-4" /> Objects · patterns · implementation</div><h1 className="max-w-4xl text-5xl font-black leading-[1.02] tracking-tight text-white md:text-7xl">Design better objects before you scale the system.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Learn SOLID principles, recognize design patterns in real products, draw UML relationships, and implement small systems with clear responsibilities.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="#problems" className="inline-flex items-center gap-2 rounded-2xl bg-white px-6 py-3 font-semibold text-ink hover:bg-cyan-100">Start a problem <ArrowRight className="h-4 w-4" /></Link><Link href="/practice-problems" className="inline-flex items-center gap-2 rounded-2xl border border-white/15 px-6 py-3 font-semibold text-white hover:bg-white/10">All practice</Link></div></div>
          <div className="glass rounded-[2rem] p-5"><div className="rounded-[1.5rem] border border-white/10 bg-ink/80 p-5"><p className="text-sm text-slate-400">Every LLD problem includes</p><div className="mt-4 space-y-3">{['Requirements and domain objects', 'UML relationship sketch', 'Core functions to implement', 'Pattern choice and trade-offs', 'TypeScript implementation starter', 'Quiz + interview rubric'].map((item, i) => <div key={item} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.03] p-3"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-cyan/15 text-xs font-bold text-cyan">{i + 1}</span><span className="text-sm font-semibold text-white">{item}</span></div>)}</div></div></div>
        </section>

        <section><div className="mb-5"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-cyan">Core concepts</p><h2 className="mt-2 text-3xl font-black text-white">A practical LLD toolkit</h2></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{lldTopics.map((topic) => <div key={topic.title} className="glass rounded-3xl p-5"><Code2 className="h-5 w-5 text-cyan" /><h3 className="mt-4 text-xl font-black text-white">{topic.title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{topic.description}</p></div>)}</div></section>

        <section className="grid gap-5 lg:grid-cols-2"><div className="glass rounded-3xl p-6"><div className="flex items-center gap-3"><Layers3 className="h-5 w-5 text-cyan" /><h2 className="text-2xl font-black text-white">SOLID in the real world</h2></div><div className="mt-5 space-y-4">{solidPrinciples.map((item) => <div key={item.name} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex items-baseline justify-between gap-3"><h3 className="font-bold text-cyan-100"><Link href={`/low-level-design/solid/${toLldSlug(item.name)}`} className="hover:text-cyan">{item.name}</Link></h3><span className="text-xs text-slate-500">{item.short}</span></div><p className="mt-2 text-sm leading-6 text-slate-300">{item.explanation}</p><p className="mt-2 text-xs leading-5 text-violet-100"><strong>Example:</strong> {item.example}</p><ul className="mt-3 space-y-1 text-xs text-slate-400">{(solidExamples[item.name] ?? []).map((example) => <li key={example}>• {example}</li>)}</ul></div>)}</div></div><div className="glass rounded-3xl p-6"><div className="flex items-center gap-3"><Boxes className="h-5 w-5 text-cyan" /><h2 className="text-2xl font-black text-white">Patterns with purpose</h2></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{designPatterns.map((pattern) => <div key={pattern.name} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex justify-between gap-2"><h3 className="font-bold text-white"><Link href={`/low-level-design/patterns/${toLldSlug(pattern.name)}`} className="hover:text-cyan">{pattern.name}</Link></h3><span className="text-[10px] uppercase tracking-wider text-cyan">{pattern.family}</span></div><p className="mt-2 text-xs leading-5 text-slate-300">{pattern.intent}</p><p className="mt-2 text-xs leading-5 text-slate-400"><strong className="text-violet-100">Real world:</strong> {pattern.realWorld}</p><ul className="mt-2 space-y-1 text-xs text-slate-500">{(patternExamples[pattern.name] ?? []).map((example) => <li key={example}>• {example}</li>)}</ul></div>)}</div></div></section>

        <section id="problems" className="scroll-mt-8 pb-12"><div className="mb-5"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-cyan">20 hands-on problems</p><h2 className="mt-2 text-3xl font-black text-white">Design, draw, implement</h2><p className="mt-2 text-slate-400">Open any problem to use the same canvas, UML notes, functions, implementation starter, patterns, and rubric.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{problems.map((problem, index) => <Link key={problem.slug} href={`/practice-problems/${problem.slug}`} className="group glass rounded-3xl p-5 transition hover:-translate-y-1 hover:border-cyan/40"><div className="flex items-start justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-brand/20 text-sm font-black text-violet-100">{index + 1}</span><span className="rounded-full border border-cyan/20 bg-cyan/10 px-2 py-1 text-xs text-cyan-100">{problem.difficulty}</span></div><h3 className="mt-4 text-xl font-black text-white">{problem.title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">Focus: {problem.focus?.join(' · ')}</p><p className="mt-3 text-xs leading-5 text-violet-100">Interview kit: UML · functions · implementation · trade-offs</p><div className="mt-4 flex flex-wrap gap-2">{problem.patterns?.map((p) => <span key={p} className="rounded-full border border-white/10 px-2 py-1 text-xs text-slate-400">{p}</span>)}</div><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-cyan">Open canvas & guide <ArrowRight className="h-4 w-4" /></span></Link>)}</div></section>
      </div>
    </main>
  );
}
