import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowRight, Boxes, CheckCircle2 } from 'lucide-react';
import { designPatterns, patternScenarios, toLldSlug } from '@/lib/low-level-design';

export function generateStaticParams() { return designPatterns.map((item) => ({ slug: toLldSlug(item.name) })); }

export default async function PatternBlogPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const item = designPatterns.find((pattern) => toLldSlug(pattern.name) === slug);
  if (!item) notFound();
  const scenario = patternScenarios[item.name];
  return <main className="min-h-screen px-6 py-8"><div className="mx-auto max-w-4xl space-y-6"><nav className="flex items-center justify-between"><div className="text-sm font-bold text-white">SystemDesign Lab · Design pattern blog</div><Link href="/low-level-design" className="inline-flex items-center gap-2 rounded-2xl border border-white/15 px-3 py-2 text-sm text-slate-200"><ArrowLeft className="h-4 w-4" /> LLD</Link></nav><article className="glass rounded-3xl p-6 md:p-10"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-400/15 text-violet-100"><Boxes /></div><span className="rounded-full border border-cyan/20 bg-cyan/10 px-3 py-1 text-xs uppercase tracking-wider text-cyan">{item.family}</span></div><h1 className="mt-6 text-4xl font-black text-white md:text-6xl">{item.name}</h1><p className="mt-5 text-lg leading-8 text-slate-300">{item.intent}</p><Block title="When this situation appears"><p>{item.useWhen}</p><p className="mt-3">Prefer this pattern when the variation is a real domain decision. If there is only one implementation and no likely change, a simple function is often clearer.</p></Block><Block title="Real-world example"><p className="text-violet-100"><strong>{item.realWorld}</strong></p><div className="mt-4 rounded-2xl border border-white/10 bg-black/20 p-4 font-mono text-xs leading-6 text-slate-200">Client → interface → interchangeable implementation<br />Controller → domain service → policy / handler</div></Block><Block title={`Scenario: ${scenario.title}`}><p>{scenario.problem}</p><div className="mt-4 flex flex-wrap items-center gap-2">{scenario.components.map((component, index) => <span key={component} className="flex items-center gap-2">{index > 0 && <span className="text-cyan">→</span>}<span className="rounded-xl border border-cyan/25 bg-cyan/10 px-3 py-2 font-mono text-xs font-bold text-cyan-100">{component}</span></span>)}</div><p className="mt-4 rounded-xl bg-black/20 p-3 font-mono text-xs text-violet-100">{scenario.flow}</p></Block><Block title="How to discuss it in an interview"><ul className="space-y-3"><Bullet>Identify the repeated conditional or coupling that motivated the pattern.</Bullet><Bullet>Draw the client, abstraction, and concrete implementations in UML.</Bullet><Bullet>Name the extension point and show one core function.</Bullet><Bullet>Explain the cost: indirection, object count, memory, or operational complexity.</Bullet></ul></Block><Link href="/low-level-design" className="mt-6 inline-flex items-center gap-2 text-cyan">See all patterns and problems <ArrowRight className="h-4 w-4" /></Link></article></div></main>;
}
function Block({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-8 border-t border-white/10 pt-6"><h2 className="text-2xl font-black text-white">{title}</h2><div className="mt-3 text-sm leading-7 text-slate-300">{children}</div></section>; }
function Bullet({ children }: { children: React.ReactNode }) { return <li className="flex gap-2"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-emerald-300" />{children}</li>; }
