import type { QuizQuestion } from './essentials';

export type RealWorldDifficulty = 'Basic' | 'Easy' | 'Medium' | 'Hard';

export type DesignDecision = {
  decision: string;
  why: string;
  wrongDirection: string;
  correction: string;
};

export type RealWorldExampleModule = {
  slug: string;
  order: number;
  title: string;
  difficulty: RealWorldDifficulty;
  summary: string;
  blogIntro: string;
  realWorldContext: string;
  keyRequirements: string[];
  architecture: string[];
  dataModel: string[];
  decisions: DesignDecision[];
  scalingNotes: string[];
  failureScenarios: {
    title: string;
    failure: string;
    recovery: string;
  }[];
  quiz: QuizQuestion[];
};

const defaultQuiz = (title: string, cacheUse: string): QuizQuestion[] => [
  {
    question: `When designing ${title}, what should drive the architecture first?`,
    options: ['Requirements and access patterns', 'Choosing trendy technology first', 'Drawing microservices immediately', 'Avoiding trade-offs'],
    answer: 'Requirements and access patterns',
    explanation: 'Real system design starts from product behavior, traffic, latency, consistency, and access patterns. Tools come after those decisions.',
  },
  {
    question: `In ${title}, when should Redis/cache be introduced?`,
    options: [cacheUse, 'Before understanding reads and writes', 'As the permanent source of truth', 'To replace all databases'],
    answer: cacheUse,
    explanation: 'Cache is useful when it matches a real read-heavy, low-latency, or counter/ranking requirement. It should not blindly replace durable storage.',
  },
];

const m = (input: Omit<RealWorldExampleModule, 'quiz'> & { cacheUse: string; quiz?: QuizQuestion[] }): RealWorldExampleModule => ({
  ...input,
  quiz: input.quiz ?? defaultQuiz(input.title, input.cacheUse),
});

export const realWorldExampleModules: RealWorldExampleModule[] = [
  m({
    slug: 'url-shortener-real-world',
    order: 1,
    title: 'URL Shortener like bit.ly',
    difficulty: 'Basic',
    summary: 'Design short link creation, redirect path, custom aliases, cache, expiry, analytics, and abuse control.',
    blogIntro: 'A URL shortener looks simple, but it teaches the complete system design journey: small write path, huge read path, cache-first redirects, durable mappings, and async analytics.',
    realWorldContext: 'Products like bit.ly and TinyURL need redirects to be extremely fast because every extra millisecond is visible to end users and advertisers.',
    keyRequirements: ['Create short URL', 'Redirect by code', 'Support custom alias and expiry', 'Track click analytics asynchronously', 'Prevent spam and malicious URLs'],
    architecture: ['Client', 'API Gateway', 'URL service', 'Redis cache', 'PostgreSQL mappings', 'Analytics queue', 'Analytics workers'],
    dataModel: ['url_mapping(code UNIQUE, long_url, user_id, expires_at, created_at)', 'click_event(code, timestamp, country, device)', 'alias_reservation(alias, user_id)'],
    decisions: [
      { decision: 'Use database as source of truth and Redis for hot redirects.', why: 'Redirect traffic is read-heavy and latency-sensitive, while mappings must be durable.', wrongDirection: 'Store mappings only in Redis because it is fast.', correction: 'Redis can evict or fail. Keep PostgreSQL/DynamoDB as source of truth and repopulate cache on miss.' },
      { decision: 'Process analytics through a queue.', why: 'Redirect must return quickly; analytics writes should not block user navigation.', wrongDirection: 'Write every click synchronously before redirecting.', correction: 'Publish a click event and let workers aggregate later.' },
      { decision: 'Rate-limit create-link API more strictly than redirect API.', why: 'Creation can be abused for spam and stresses writes; redirects are public high-volume reads.', wrongDirection: 'Apply the same low limit to every endpoint.', correction: 'Use endpoint-specific limits and abuse scanning.' },
    ],
    scalingNotes: ['Cache popular code-to-URL mappings.', 'Use unique constraints for aliases.', 'Shard by code hash when one DB cannot hold total data.', 'Use CDN/edge caching for extremely popular links.'],
    failureScenarios: [
      { title: 'Redis outage', failure: 'Redirect cache is unavailable.', recovery: 'Fallback to database reads, reduce TTL churn, and protect DB with rate limits and circuit breakers.' },
      { title: 'Analytics worker backlog', failure: 'Clicks are delayed but redirects still work.', recovery: 'Scale workers, monitor queue age, and preserve events in durable queue.' },
    ],
    cacheUse: 'For hot short-code to long-URL lookups after database writes are durable',
  }),
  m({
    slug: 'pastebin-text-sharing',
    order: 2,
    title: 'Code/Text Sharing like Pastebin',
    difficulty: 'Basic',
    summary: 'Design paste creation, public/private links, expiry, syntax metadata, moderation, and read-heavy access.',
    blogIntro: 'Pastebin-style systems are excellent beginner designs because they combine simple APIs with real product concerns: privacy, expiry, abuse, and read-heavy sharing.',
    realWorldContext: 'Developers share logs, snippets, and notes. Some pastes are public and viral; others must expire or remain unlisted.',
    keyRequirements: ['Create paste', 'Read paste by ID', 'Optional expiry', 'Public/private/unlisted visibility', 'Syntax highlighting metadata', 'Report abuse'],
    architecture: ['Client', 'API Gateway', 'Paste service', 'Metadata DB', 'Object/blob storage', 'Redis cache', 'Moderation queue'],
    dataModel: ['paste(id, owner_id, visibility, expires_at, object_key, language)', 'paste_version(paste_id, object_key, created_at)', 'abuse_report(paste_id, reason, status)'],
    decisions: [
      { decision: 'Store large paste body in object storage and metadata in DB.', why: 'This keeps DB rows small and lets storage scale cheaply.', wrongDirection: 'Store every large text body directly in one relational row.', correction: 'Use DB for metadata and object storage for large content.' },
      { decision: 'Cache public hot pastes.', why: 'Popular pastes may be read thousands of times and rarely change.', wrongDirection: 'Hit the DB and object storage for every read.', correction: 'Cache rendered/read result with TTL and invalidate on edit/delete.' },
      { decision: 'Use expiry cleanup asynchronously.', why: 'Deleting expired content can run in background without blocking reads.', wrongDirection: 'Scan the whole table on every read.', correction: 'Check expiry by indexed field and use scheduled cleanup workers.' },
    ],
    scalingNotes: ['Use CDN for public paste reads.', 'Index by id, owner_id, expires_at.', 'Use abuse detection before making public content discoverable.', 'Use short IDs with collision protection.'],
    failureScenarios: [
      { title: 'Viral paste', failure: 'One paste receives huge traffic.', recovery: 'Serve from CDN/Redis and protect origin.' },
      { title: 'Moderation delay', failure: 'Malicious paste remains accessible.', recovery: 'Use report queue, automated scanning, and emergency takedown path.' },
    ],
    cacheUse: 'For public hot pastes and rendered syntax-highlighted content',
  }),
  m({
    slug: 'rate-limiter-design',
    order: 3,
    title: 'Rate Limiter for APIs',
    difficulty: 'Easy',
    summary: 'Design per-user/IP quotas, token buckets, sliding windows, Redis counters, and 429 responses.',
    blogIntro: 'Rate limiters teach a core real-world lesson: protect shared infrastructure before traffic reaches expensive services.',
    realWorldContext: 'Stripe, GitHub, Twitter/X, and cloud APIs all use rate limits to prevent abuse and maintain fairness.',
    keyRequirements: ['Limit by API key/user/IP', 'Support route-specific limits', 'Allow paid tiers', 'Return retry-after', 'Expose usage metrics'],
    architecture: ['Client', 'API Gateway', 'Rate limiter', 'Redis/token store', 'Backend service', 'Metrics pipeline'],
    dataModel: ['limit_rule(route, plan, max_requests, window)', 'bucket(key, tokens, last_refill_at)', 'limit_event(key, route, allowed, timestamp)'],
    decisions: [
      { decision: 'Run limiter at gateway/edge.', why: 'Bad traffic should be rejected before reaching services and databases.', wrongDirection: 'Rate-limit only deep inside business services.', correction: 'Apply coarse limits at edge and fine-grained limits in services if needed.' },
      { decision: 'Use token bucket for burst-friendly APIs.', why: 'It allows short bursts while enforcing average rate.', wrongDirection: 'Use fixed window for every use case.', correction: 'Pick algorithm based on behavior: token bucket for bursts, sliding window for smoother fairness.' },
      { decision: 'Use shared Redis counters for global limits.', why: 'Multiple gateway instances need consistent quota state.', wrongDirection: 'Each gateway keeps only local counters.', correction: 'Local counters are approximate; use shared storage when global correctness matters.' },
    ],
    scalingNotes: ['Keep limiter lookup fast.', 'Use Lua/scripts or atomic operations.', 'Fail open or fail closed based on endpoint risk.', 'Monitor blocked requests and false positives.'],
    failureScenarios: [
      { title: 'Redis limiter unavailable', failure: 'Limiter cannot read quota state.', recovery: 'Fail open for low-risk reads, fail closed for login/payment abuse paths, and alert immediately.' },
      { title: 'Clock/window boundary burst', failure: 'Fixed window allows double burst near boundaries.', recovery: 'Use sliding window or token bucket.' },
    ],
    cacheUse: 'For fast shared counters/token buckets with TTL per limit window',
  }),
  m({
    slug: 'notification-service-design',
    order: 4,
    title: 'Notification Service',
    difficulty: 'Easy',
    summary: 'Design email/SMS/push delivery with queues, templates, preferences, retries, and provider fallback.',
    blogIntro: 'Notification systems are everywhere. The key lesson is decoupling product events from unreliable external providers.',
    realWorldContext: 'E-commerce, banking, social, and SaaS products send transactional alerts, marketing campaigns, and mobile pushes.',
    keyRequirements: ['Send email/SMS/push', 'Respect preferences', 'Template rendering', 'Retry failures', 'Track delivery status', 'Support provider fallback'],
    architecture: ['Product service', 'Event bus/queue', 'Notification orchestrator', 'Template service', 'Channel workers', 'Providers', 'Delivery log DB'],
    dataModel: ['notification(id, user_id, type, payload, status)', 'user_preference(user_id, channel, enabled)', 'delivery_attempt(notification_id, provider, status, retry_count)'],
    decisions: [
      { decision: 'Use queue between product and notification workers.', why: 'Provider calls are slow and unreliable; product API should not wait.', wrongDirection: 'Send SMS/email synchronously inside checkout or signup.', correction: 'Publish event, return response, and deliver asynchronously.' },
      { decision: 'Store delivery attempts.', why: 'You need auditability, debugging, and retry visibility.', wrongDirection: 'Only log to stdout and lose state.', correction: 'Persist status and attempts in delivery log table.' },
      { decision: 'Use fallback providers for critical channels.', why: 'External providers fail or rate-limit.', wrongDirection: 'Depend on one SMS/email vendor with no fallback.', correction: 'Route critical notifications to secondary provider after configured failure threshold.' },
    ],
    scalingNotes: ['Separate workers by channel.', 'Use idempotency keys.', 'Backoff retries to respect provider limits.', 'Monitor queue age and DLQ size.'],
    failureScenarios: [
      { title: 'Provider outage', failure: 'Email/SMS provider returns 5xx.', recovery: 'Retry with backoff and fail over critical messages.' },
      { title: 'Duplicate sends', failure: 'Worker retry sends same message twice.', recovery: 'Use idempotency keys and provider-side dedup where available.' },
    ],
    cacheUse: 'For frequently read user preferences/templates, not as delivery source of truth',
  }),
  m({
    slug: 'file-storage-service',
    order: 5,
    title: 'File Storage Service like Google Drive',
    difficulty: 'Medium',
    summary: 'Design upload/download, metadata, permissions, sharing, resumable upload, object storage, and CDN.',
    blogIntro: 'File storage design teaches separation of metadata and bytes, secure sharing, resumable upload, and object storage economics.',
    realWorldContext: 'Google Drive, Dropbox, Slack, and Notion all store files while enforcing permissions and serving downloads globally.',
    keyRequirements: ['Upload/download files', 'Resume large uploads', 'Share files/folders', 'Permission checks', 'Versioning', 'Virus scanning'],
    architecture: ['Client', 'File API', 'Signed URL service', 'Object storage', 'Metadata DB', 'Scan queue', 'CDN'],
    dataModel: ['file(id, owner_id, name, object_key, size, checksum, status)', 'folder(id, parent_id)', 'permission(file_id, principal_id, role)', 'upload_session(file_id, part_count)'],
    decisions: [
      { decision: 'Use object storage for bytes and DB for metadata.', why: 'Large binary data is cheaper and more scalable in blob/object stores.', wrongDirection: 'Push every byte through app servers into SQL.', correction: 'Use signed URLs and direct multipart upload.' },
      { decision: 'Use short-lived signed URLs for downloads.', why: 'Private files need authorization without exposing permanent public URLs.', wrongDirection: 'Make object storage bucket public.', correction: 'Authorize in API, then issue scoped temporary URL.' },
      { decision: 'Scan files asynchronously after upload.', why: 'Virus scanning can be slow and should not block upload completion forever.', wrongDirection: 'Mark files safe immediately.', correction: 'Use pending status until scan worker approves.' },
    ],
    scalingNotes: ['Use multipart upload.', 'Cache metadata carefully.', 'CDN public/shared downloads.', 'Use checksums for dedup and integrity.'],
    failureScenarios: [
      { title: 'Upload interrupted', failure: 'Large upload fails at 95%.', recovery: 'Resume missing parts using upload session.' },
      { title: 'Permission leak', failure: 'Shared URL gives access after permission revoked.', recovery: 'Use short TTL signed URLs and check permissions before issuing.' },
    ],
    cacheUse: 'For file metadata and permission decisions with short TTL after DB authorization',
  }),
  m({
    slug: 'search-autocomplete',
    order: 6,
    title: 'Search Autocomplete',
    difficulty: 'Medium',
    summary: 'Design typeahead suggestions using prefix indexes, ranking, caching, and near-real-time updates.',
    blogIntro: 'Autocomplete is a low-latency system where every keystroke can become a request. The design balances fast prefix lookup and ranking freshness.',
    realWorldContext: 'Google, Amazon, YouTube, and app stores all use autocomplete to reduce user effort and guide discovery.',
    keyRequirements: ['Return suggestions by prefix', 'Rank by popularity/personalization', 'Low latency per keystroke', 'Update index from new data', 'Handle typo/locale'],
    architecture: ['Client', 'Search API', 'Suggestion service', 'Prefix index/trie', 'Ranking store', 'Redis cache', 'Indexing pipeline'],
    dataModel: ['suggestion(prefix, term, score, locale)', 'query_log(query, user_id, timestamp)', 'term_stats(term, popularity, freshness)'],
    decisions: [
      { decision: 'Precompute top suggestions per prefix.', why: 'Keystroke latency must be very low.', wrongDirection: 'Run full database search on every keypress.', correction: 'Build prefix index/trie and serve top-N quickly.' },
      { decision: 'Cache popular prefixes.', why: 'Prefixes like “a”, “i”, “new” are extremely hot.', wrongDirection: 'Treat every prefix equally.', correction: 'Cache hot prefixes and use request coalescing.' },
      { decision: 'Update index asynchronously.', why: 'Ranking signals come from logs and can tolerate slight delay.', wrongDirection: 'Rebuild index synchronously on every query.', correction: 'Use stream/batch indexing pipeline.' },
    ],
    scalingNotes: ['Debounce client requests.', 'Use CDN/edge cache for anonymous common prefixes.', 'Shard by prefix or language.', 'Monitor p95 latency and cache hit rate.'],
    failureScenarios: [
      { title: 'Hot prefix overload', failure: 'Short prefixes overwhelm service.', recovery: 'Cache top short-prefix results and require minimum prefix length.' },
      { title: 'Bad suggestions', failure: 'Spam terms enter autocomplete.', recovery: 'Use moderation filters and ranking penalties.' },
    ],
    cacheUse: 'For hot prefix-to-top-suggestions results',
  }),
  m({
    slug: 'real-time-leaderboard',
    order: 7,
    title: 'Real-time Leaderboard',
    difficulty: 'Medium',
    summary: 'Design score updates, top-K, rank lookup, seasons, Redis sorted sets, and sharding.',
    blogIntro: 'Leaderboards are a clean example of choosing the right data structure for the access pattern: update scores and query top rankings fast.',
    realWorldContext: 'Games, fitness apps, learning apps, and trading platforms use leaderboards to show rank and motivate engagement.',
    keyRequirements: ['Update player score', 'Show top-K', 'Show user rank', 'Support seasons/regions', 'Prevent cheating', 'Real-time updates'],
    architecture: ['Game service', 'Score API', 'Validation service', 'Redis sorted sets', 'Persistent DB', 'Realtime gateway'],
    dataModel: ['score_event(user_id, score_delta, event_id)', 'leaderboard(season, region, user_id, score)', 'user_rank_cache(user_id, rank)'],
    decisions: [
      { decision: 'Use Redis sorted sets for active leaderboard.', why: 'They support score updates, top-K, and rank lookup efficiently.', wrongDirection: 'Sort millions of rows in SQL for every request.', correction: 'Use DB as durable history and Redis sorted set as serving index.' },
      { decision: 'Persist score events durably.', why: 'Redis can be rebuilt from events if needed.', wrongDirection: 'Keep only in-memory score state.', correction: 'Append score events to durable storage/stream.' },
      { decision: 'Partition by season/game/region.', why: 'One global leaderboard can become too large and not product-relevant.', wrongDirection: 'Put all users in one massive sorted set forever.', correction: 'Scope leaderboards and archive old seasons.' },
    ],
    scalingNotes: ['Use anti-cheat validation.', 'Push updates over WebSockets sparingly.', 'Cache user rank for hot users.', 'Shard large leaderboards by region or bracket.'],
    failureScenarios: [
      { title: 'Redis lost data', failure: 'Leaderboard cache disappears.', recovery: 'Rebuild from durable score events.' },
      { title: 'Cheating spike', failure: 'Fake scores dominate top ranks.', recovery: 'Validate events and quarantine suspicious scores.' },
    ],
    cacheUse: 'As the active sorted ranking index backed by durable score events',
  }),
  m({
    slug: 'distributed-id-generator',
    order: 8,
    title: 'Distributed ID Generator',
    difficulty: 'Easy',
    summary: 'Design unique sortable IDs using Snowflake-style timestamps, worker IDs, sequences, and clock drift handling.',
    blogIntro: 'ID generation seems tiny, but it affects database indexes, ordering, scale, and availability across services.',
    realWorldContext: 'Twitter Snowflake-style IDs, order IDs, event IDs, and message IDs need uniqueness without one central bottleneck.',
    keyRequirements: ['Generate unique IDs', 'High throughput', 'Rough ordering', 'No single DB sequence bottleneck', 'Handle clock drift'],
    architecture: ['Client service', 'ID generator library/service', 'Worker ID allocator', 'Clock monitor', 'Metrics'],
    dataModel: ['id = timestamp_bits + worker_id_bits + sequence_bits', 'worker_assignment(worker_id, host, lease_expires_at)'],
    decisions: [
      { decision: 'Use Snowflake-style IDs for high scale.', why: 'It avoids central sequence bottleneck and preserves rough time ordering.', wrongDirection: 'Use one SQL auto-increment sequence for all global traffic.', correction: 'Use timestamp + worker id + sequence bits.' },
      { decision: 'Lease worker IDs.', why: 'Two workers with same ID can generate collisions.', wrongDirection: 'Hardcode worker IDs manually forever.', correction: 'Use coordination service or deployment-time unique assignment.' },
      { decision: 'Detect clock rollback.', why: 'Time-based IDs can duplicate or go out of order if clocks move backward.', wrongDirection: 'Ignore clock drift.', correction: 'Pause, use logical sequence, or alert when clock moves backward.' },
    ],
    scalingNotes: ['Keep generation local for low latency.', 'Monitor sequence exhaustion per millisecond.', 'Plan bit allocation for lifetime.', 'Document ordering guarantees clearly.'],
    failureScenarios: [
      { title: 'Duplicate worker ID', failure: 'Two nodes generate same ID range.', recovery: 'Use leases and collision monitoring.' },
      { title: 'Clock rollback', failure: 'IDs become non-monotonic or duplicate.', recovery: 'Block generation briefly or use logical clock fallback.' },
    ],
    cacheUse: 'Not usually needed; ID generation should be local and deterministic',
  }),
  m({
    slug: 'ecommerce-product-catalog',
    order: 9,
    title: 'E-commerce Product Catalog',
    difficulty: 'Medium',
    summary: 'Design product pages, inventory visibility, search/filtering, pricing, caching, and CDN delivery.',
    blogIntro: 'A catalog system teaches read-heavy design, cache invalidation, search indexes, and the difference between product data and inventory correctness.',
    realWorldContext: 'Amazon, Shopify, Flipkart, and marketplaces serve product pages at huge volume while prices and inventory change often.',
    keyRequirements: ['Browse product pages', 'Search/filter products', 'Show price and inventory', 'Support sellers/categories', 'Handle flash-sale traffic'],
    architecture: ['Client', 'Catalog API', 'Product DB', 'Search index', 'Redis cache', 'Inventory service', 'CDN'],
    dataModel: ['product(id, seller_id, title, description, category)', 'sku(id, product_id, price, inventory_count)', 'category(id, parent_id)', 'product_index(document)'],
    decisions: [
      { decision: 'Use search index for search/filter, DB for source of truth.', why: 'Search needs inverted indexes and ranking; DB keeps canonical data.', wrongDirection: 'Run complex LIKE/filter queries on primary DB for all searches.', correction: 'Sync product data into Elasticsearch/OpenSearch-style index.' },
      { decision: 'Cache product detail pages but keep inventory fresher.', why: 'Descriptions change rarely; inventory/price may change often.', wrongDirection: 'Cache all product information with one long TTL.', correction: 'Split static product cache from dynamic price/inventory fetch.' },
      { decision: 'Use CDN for images/static assets.', why: 'Product images dominate bandwidth and should be close to users.', wrongDirection: 'Serve all images through application servers.', correction: 'Store images in object storage and deliver through CDN.' },
    ],
    scalingNotes: ['Use cache warming for popular products.', 'Index category and seller queries.', 'Protect inventory service during flash sales.', 'Use event-driven index updates.'],
    failureScenarios: [
      { title: 'Search index lag', failure: 'New product not searchable immediately.', recovery: 'Show from seller dashboard DB and communicate indexing delay.' },
      { title: 'Stale inventory', failure: 'Product appears in stock but is sold out.', recovery: 'Validate inventory at checkout/reservation step.' },
    ],
    cacheUse: 'For product detail, category pages, and hot search results while keeping price/inventory carefully refreshed',
  }),
  m({
    slug: 'shopping-cart-checkout',
    order: 10,
    title: 'Shopping Cart and Checkout',
    difficulty: 'Medium',
    summary: 'Design cart state, checkout, inventory reservation, payment idempotency, and order creation.',
    blogIntro: 'Checkout systems teach correctness. Unlike feeds or analytics, duplicate payments and oversold inventory are unacceptable.',
    realWorldContext: 'Every e-commerce platform needs carts that feel fast and checkout flows that are reliable under retries and payment failures.',
    keyRequirements: ['Add/remove cart items', 'Calculate totals', 'Reserve inventory', 'Create order', 'Process payment', 'Handle retries safely'],
    architecture: ['Client', 'Cart service', 'Pricing service', 'Inventory service', 'Order service', 'Payment gateway', 'Event queue'],
    dataModel: ['cart(user_id, items, updated_at)', 'inventory_reservation(id, sku_id, qty, expires_at)', 'order(id, user_id, status, total)', 'payment(idempotency_key, order_id, status)'],
    decisions: [
      { decision: 'Use idempotency keys for checkout/payment.', why: 'Clients retry when network fails; duplicate charges must be prevented.', wrongDirection: 'Create a new payment on every retry.', correction: 'Store idempotency key and return same result for repeated request.' },
      { decision: 'Reserve inventory before payment capture.', why: 'Prevents selling the same item to many users.', wrongDirection: 'Only check inventory after payment succeeds.', correction: 'Create time-limited reservation and release on timeout/failure.' },
      { decision: 'Cart can be eventually consistent, order cannot.', why: 'Cart UX can tolerate small delays; order/payment need correctness.', wrongDirection: 'Treat every cart update like a financial transaction.', correction: 'Use strong consistency only where business correctness requires it.' },
    ],
    scalingNotes: ['Cache product/pricing metadata.', 'Use saga/workflow for checkout steps.', 'Expire abandoned reservations.', 'Emit order events for email/fulfillment asynchronously.'],
    failureScenarios: [
      { title: 'Payment timeout', failure: 'Client does not know if payment succeeded.', recovery: 'Use idempotency key and payment status reconciliation.' },
      { title: 'Reservation leak', failure: 'Inventory remains locked after failed checkout.', recovery: 'Use TTL and cleanup jobs.' },
    ],
    cacheUse: 'For cart reads and product/pricing metadata, not for final order/payment correctness',
  }),
  m({
    slug: 'ride-sharing-location',
    order: 11,
    title: 'Ride Sharing Location System',
    difficulty: 'Hard',
    summary: 'Design driver location ingestion, geo-indexing, nearby driver search, real-time updates, and dispatch.',
    blogIntro: 'Ride sharing location is a high-write real-time system where freshness matters more than perfect historical accuracy.',
    realWorldContext: 'Uber, Lyft, Ola, and Grab continuously ingest driver coordinates and match riders with nearby drivers.',
    keyRequirements: ['Ingest driver location', 'Find nearby drivers', 'Update rider map', 'Dispatch ride request', 'Handle stale locations'],
    architecture: ['Driver app', 'Location gateway', 'Stream processor', 'Geo index', 'Dispatch service', 'Rider app', 'Location history store'],
    dataModel: ['driver_location(driver_id, lat, lng, geohash, updated_at)', 'ride_request(id, rider_id, pickup_geohash, status)', 'driver_status(driver_id, available, vehicle_type)'],
    decisions: [
      { decision: 'Store latest location in fast geo index.', why: 'Nearby search needs low latency and fresh coordinates.', wrongDirection: 'Query a relational table with full scan for every rider.', correction: 'Use geohash/S2 cells/Redis GEO or specialized geo index.' },
      { decision: 'Stream location updates instead of synchronous heavy writes.', why: 'Drivers send frequent updates; pipelines must absorb bursts.', wrongDirection: 'Write every coordinate synchronously to many databases.', correction: 'Update latest-location store quickly and archive history asynchronously.' },
      { decision: 'Expire stale driver locations.', why: 'A driver who stopped sending updates should not appear available.', wrongDirection: 'Keep last known location forever.', correction: 'Use TTL/heartbeat and remove stale drivers from dispatch index.' },
    ],
    scalingNotes: ['Partition by city/geohash.', 'Throttle location update frequency.', 'Use WebSockets for rider map updates.', 'Separate latest location from history analytics.'],
    failureScenarios: [
      { title: 'Location stream lag', failure: 'Rider sees stale driver positions.', recovery: 'Monitor lag and degrade by reducing update frequency or using last-known with freshness label.' },
      { title: 'Geo hot cell', failure: 'Airport/stadium cell overloads.', recovery: 'Subdivide hot cells and add regional capacity.' },
    ],
    cacheUse: 'For latest available driver locations with short TTL and freshness checks',
  }),
  m({
    slug: 'twitter-x-feed',
    order: 12,
    title: 'Twitter / X Home Feed',
    difficulty: 'Hard',
    summary: 'Design posts, follow graph, fanout, ranking, timeline cache, celebrity users, and freshness.',
    blogIntro: 'Feeds are hard because they mix social graph scale, ranking, freshness, and hot accounts with millions of followers.',
    realWorldContext: 'Twitter/X, Instagram, LinkedIn, and TikTok all build personalized feeds from a mix of follow graph, ranking, and recommendations.',
    keyRequirements: ['Create post', 'Follow/unfollow', 'Read home feed', 'Rank posts', 'Handle celebrity accounts', 'Support media'],
    architecture: ['Post service', 'Follow graph', 'Fanout workers', 'Timeline cache', 'Ranking service', 'Media service', 'Feed API'],
    dataModel: ['post(id, author_id, body, media_ids, created_at)', 'follow(follower_id, followee_id)', 'home_timeline(user_id, post_id, score)', 'author_outbox(author_id, post_id)'],
    decisions: [
      { decision: 'Use hybrid fanout.', why: 'Normal users can fanout-on-write; celebrities need fanout-on-read to avoid massive write amplification.', wrongDirection: 'Fanout every post to every follower synchronously.', correction: 'Precompute normal timelines and merge celebrity/outbox posts at read time.' },
      { decision: 'Cache home timeline.', why: 'Feed reads are frequent and need low latency.', wrongDirection: 'Rebuild full feed from follow graph on every request.', correction: 'Serve from timeline cache and refresh asynchronously.' },
      { decision: 'Accept eventual consistency for feed freshness.', why: 'A few seconds delay is acceptable compared to global expensive consistency.', wrongDirection: 'Require every follower to see every post instantly with strong consistency.', correction: 'Expose refresh behavior and track fanout lag.' },
    ],
    scalingNotes: ['Use queues for fanout.', 'Partition timelines by user_id.', 'Keep media delivery in CDN.', 'Monitor celebrity fanout and ranking latency.'],
    failureScenarios: [
      { title: 'Celebrity post storm', failure: 'Fanout queue explodes.', recovery: 'Switch account to read-time merge and prioritize active users.' },
      { title: 'Timeline cache miss storm', failure: 'Millions of users rebuild feeds from DB.', recovery: 'Warm cache and use fallback stale timelines.' },
    ],
    cacheUse: 'For home timelines, author outboxes, and hot ranked feed pages',
  }),
  m({
    slug: 'messaging-chat-app',
    order: 13,
    title: 'Messaging App / Chat',
    difficulty: 'Medium',
    summary: 'Design real-time messaging with WebSockets, persistence, ordering, delivery receipts, presence, and offline sync.',
    blogIntro: 'Chat systems teach real-time communication plus durable history. The user expects instant delivery, but the system must survive reconnects and offline devices.',
    realWorldContext: 'WhatsApp, Slack, Discord, and Messenger deliver messages across many devices with presence and read receipts.',
    keyRequirements: ['Send/receive messages', 'Group chat', 'Message history', 'Delivery/read receipts', 'Presence', 'Offline sync'],
    architecture: ['Client', 'WebSocket gateway', 'Chat service', 'Message store', 'Fanout queue', 'Presence store', 'Push notification service'],
    dataModel: ['conversation(id, type)', 'message(id, conversation_id, sender_id, body, created_at)', 'membership(conversation_id, user_id)', 'receipt(message_id, user_id, status)'],
    decisions: [
      { decision: 'Use WebSockets for online delivery and DB for history.', why: 'Realtime path and durable storage solve different needs.', wrongDirection: 'Keep messages only in WebSocket server memory.', correction: 'Persist messages before/while fanout and replay missed messages on reconnect.' },
      { decision: 'Partition messages by conversation.', why: 'Conversation is the natural access pattern for history and ordering.', wrongDirection: 'Store all messages in one global ordered table.', correction: 'Shard by conversation_id or user_id depending on scale.' },
      { decision: 'Use push notifications for offline users.', why: 'Offline devices cannot receive WebSocket events.', wrongDirection: 'Assume every user is always connected.', correction: 'Track presence and route offline alerts through notification service.' },
    ],
    scalingNotes: ['Sticky or connection-aware WebSocket routing.', 'Backpressure for large groups.', 'Store presence in Redis with TTL.', 'Use sequence numbers for ordering.'],
    failureScenarios: [
      { title: 'Gateway disconnect', failure: 'Users lose WebSocket connection.', recovery: 'Reconnect and fetch missed messages after last acknowledged sequence.' },
      { title: 'Duplicate delivery', failure: 'Retry sends same message twice.', recovery: 'Use client message ID/idempotency.' },
    ],
    cacheUse: 'For presence, recent messages, and conversation metadata with TTL',
  }),
  m({
    slug: 'video-streaming-service',
    order: 14,
    title: 'Video Streaming Service like YouTube/Netflix',
    difficulty: 'Hard',
    summary: 'Design upload, transcoding, metadata, CDN delivery, adaptive bitrate, recommendations, and global playback.',
    blogIntro: 'Video platforms are large systems because upload, processing, storage, and playback are all different workloads.',
    realWorldContext: 'YouTube, Netflix, Vimeo, and TikTok process huge media files and serve them globally at low buffering rates.',
    keyRequirements: ['Upload video', 'Transcode into multiple qualities', 'Stream playback', 'Store metadata', 'Generate thumbnails', 'Serve globally through CDN'],
    architecture: ['Uploader', 'Upload API', 'Object storage', 'Transcode queue', 'Transcoder workers', 'Metadata DB', 'CDN', 'Playback API'],
    dataModel: ['video(id, owner_id, title, status, duration)', 'rendition(video_id, codec, resolution, bitrate, object_key)', 'view_event(video_id, user_id, timestamp)'],
    decisions: [
      { decision: 'Transcode asynchronously.', why: 'Encoding is CPU-heavy and slow.', wrongDirection: 'Transcode inside upload request.', correction: 'Upload raw file, enqueue job, and update status when renditions are ready.' },
      { decision: 'Use CDN for playback segments.', why: 'Playback bandwidth is massive and global.', wrongDirection: 'Stream every video from origin app server.', correction: 'Store segments in object storage and distribute through CDN.' },
      { decision: 'Use adaptive bitrate renditions.', why: 'Users have different devices and network conditions.', wrongDirection: 'Store only one large video file.', correction: 'Generate multiple resolutions/bitrates and let player switch.' },
    ],
    scalingNotes: ['Chunk uploads.', 'Use separate queues per quality/priority.', 'Track rebuffering metrics.', 'Cache metadata and manifests.'],
    failureScenarios: [
      { title: 'Transcoding backlog', failure: 'New videos remain processing for hours.', recovery: 'Autoscale workers and prioritize popular/short videos.' },
      { title: 'CDN miss storm', failure: 'Origin storage overloaded.', recovery: 'Prewarm popular content and tune cache headers.' },
    ],
    cacheUse: 'For video metadata, manifests, thumbnails, and CDN edge video segments',
  }),
  m({
    slug: 'web-crawler',
    order: 15,
    title: 'Web Crawler',
    difficulty: 'Hard',
    summary: 'Design URL frontier, robots.txt, politeness, deduplication, distributed workers, parsing, and freshness.',
    blogIntro: 'A crawler is a distributed scheduling problem: decide what to crawl, when to crawl, and how not to harm external websites.',
    realWorldContext: 'Search engines, SEO tools, security scanners, and archive systems crawl billions of web pages.',
    keyRequirements: ['Discover URLs', 'Respect robots.txt', 'Avoid duplicate crawl', 'Throttle per domain', 'Parse content', 'Refresh important pages'],
    architecture: ['URL frontier', 'Scheduler', 'Crawler workers', 'Robots cache', 'Content parser', 'Dedup store', 'Index pipeline'],
    dataModel: ['url(url_hash, url, domain, priority, next_crawl_at)', 'crawl_result(url_hash, status, content_hash)', 'robots_rule(domain, rules, fetched_at)'],
    decisions: [
      { decision: 'Use per-domain politeness queues.', why: 'You must avoid overwhelming external sites.', wrongDirection: 'Let all workers hit the same domain concurrently.', correction: 'Throttle by host/domain and respect crawl delay.' },
      { decision: 'Deduplicate URLs and content.', why: 'The web has duplicate links and mirrored pages.', wrongDirection: 'Crawl every discovered URL blindly.', correction: 'Normalize URLs and use URL/content hashes.' },
      { decision: 'Prioritize frontier by importance and freshness.', why: 'Not all pages need the same crawl frequency.', wrongDirection: 'Use simple FIFO forever.', correction: 'Score URLs by importance, change rate, and last crawl time.' },
    ],
    scalingNotes: ['Partition frontier by domain hash.', 'Cache robots.txt.', 'Use retries with backoff.', 'Separate fetch from parse/index pipelines.'],
    failureScenarios: [
      { title: 'Crawler trap', failure: 'Infinite generated URLs consume crawl budget.', recovery: 'Detect patterns, cap depth/params, and blacklist traps.' },
      { title: 'Domain overload', failure: 'Crawler causes load on a site.', recovery: 'Enforce politeness and emergency domain block.' },
    ],
    cacheUse: 'For robots.txt rules, DNS lookups, and recently fetched duplicate metadata',
  }),
  m({
    slug: 'concert-ticket-sale',
    order: 16,
    title: 'Concert Ticket Sale System',
    difficulty: 'Hard',
    summary: 'Design high-demand inventory, waiting rooms, reservations, fairness, payment, and anti-bot controls.',
    blogIntro: 'Ticketing is a correctness-heavy system under extreme burst traffic. The hardest requirement is fairness without overselling.',
    realWorldContext: 'Ticketmaster-like platforms receive massive spikes when popular concerts or sports events go on sale.',
    keyRequirements: ['Browse events', 'Join waiting room', 'Reserve seats', 'Checkout payment', 'Prevent oversell', 'Fight bots'],
    architecture: ['Client', 'Waiting room', 'API Gateway', 'Inventory service', 'Reservation store', 'Payment service', 'Order service'],
    dataModel: ['event(id, venue_id, sale_start)', 'seat(id, event_id, status)', 'reservation(id, seat_id, user_id, expires_at)', 'order(id, reservation_id, payment_status)'],
    decisions: [
      { decision: 'Use waiting room before inventory APIs.', why: 'Inventory service cannot handle unlimited burst traffic.', wrongDirection: 'Let every user hit seat selection at sale time.', correction: 'Queue users and admit at controlled rate.' },
      { decision: 'Use short-lived seat reservations.', why: 'Prevents two users buying same seat while payment is pending.', wrongDirection: 'Mark seat sold only after payment without reservation.', correction: 'Reserve seat with TTL and release if payment fails.' },
      { decision: 'Use strong consistency for inventory.', why: 'Overselling tickets is unacceptable.', wrongDirection: 'Use eventually consistent counters for final seat sale.', correction: 'Use transactional reservation/compare-and-set on seat state.' },
    ],
    scalingNotes: ['Precompute event/seat maps.', 'Use anti-bot checks.', 'Separate browsing from checkout.', 'Use idempotent payment/order APIs.'],
    failureScenarios: [
      { title: 'Payment succeeds but order fails', failure: 'User charged without ticket.', recovery: 'Use saga reconciliation and refund/complete order workflow.' },
      { title: 'Reservation leak', failure: 'Seats stay locked.', recovery: 'TTL expiration and cleanup workers.' },
    ],
    cacheUse: 'For event details and seat map display, not for final inventory ownership',
  }),
  m({
    slug: 'distributed-cache-design',
    order: 17,
    title: 'Distributed Cache like Redis Cluster',
    difficulty: 'Hard',
    summary: 'Design sharded cache nodes, consistent hashing, replication, eviction, failover, and hot-key handling.',
    blogIntro: 'Building a cache teaches what managed caches hide: partitioning, replication, memory pressure, and failure recovery.',
    realWorldContext: 'Large platforms use distributed caches to serve hot data, sessions, counters, and computed objects at low latency.',
    keyRequirements: ['Set/get/delete keys', 'TTL expiration', 'Eviction policy', 'Shard keys', 'Replicate data', 'Handle node failures'],
    architecture: ['Client library', 'Hash ring/router', 'Cache nodes', 'Replica nodes', 'Cluster manager', 'Persistent DB fallback'],
    dataModel: ['key -> value + ttl + version', 'shard_map(range, primary, replicas)', 'node_health(node_id, status)'],
    decisions: [
      { decision: 'Use consistent hashing with virtual nodes.', why: 'Minimizes key movement when nodes change.', wrongDirection: 'Use hash(key) % nodeCount directly.', correction: 'Use hash ring/vnodes or managed slot map.' },
      { decision: 'Use eviction policy based on workload.', why: 'Memory is finite and wrong eviction hurts hit rate.', wrongDirection: 'Never evict until node crashes.', correction: 'Choose LRU/LFU/TTL and monitor memory pressure.' },
      { decision: 'Replicate hot/important keys.', why: 'Single-node ownership can fail or overload.', wrongDirection: 'One copy only for every key.', correction: 'Use replicas and hot-key spreading when needed.' },
    ],
    scalingNotes: ['Monitor hit rate.', 'Use request coalescing.', 'Avoid huge values.', 'Plan resharding and warmup.'],
    failureScenarios: [
      { title: 'Cache stampede', failure: 'Many misses hit DB at once.', recovery: 'Use locking/request coalescing, jittered TTL, and warmup.' },
      { title: 'Hot key overload', failure: 'One key saturates a node.', recovery: 'Replicate hot key or add local/CDN cache.' },
    ],
    cacheUse: 'This is the cache system itself; use it for hot, recomputable, low-latency data',
  }),
  m({
    slug: 'payment-processing-system',
    order: 18,
    title: 'Payment Processing System',
    difficulty: 'Hard',
    summary: 'Design payment intent, idempotency, provider integration, ledger, reconciliation, fraud checks, and webhooks.',
    blogIntro: 'Payment systems are high-stakes: correctness, auditability, and idempotency matter more than raw speed.',
    realWorldContext: 'Stripe, Razorpay, PayPal, and checkout systems coordinate merchants, banks, cards, fraud checks, and refunds.',
    keyRequirements: ['Create payment intent', 'Confirm payment', 'Handle provider webhook', 'Prevent duplicate charge', 'Refund', 'Reconcile ledger'],
    architecture: ['Client', 'Payment API', 'Fraud service', 'Provider adapter', 'Ledger DB', 'Webhook handler', 'Reconciliation jobs'],
    dataModel: ['payment_intent(id, amount, currency, status, idempotency_key)', 'ledger_entry(id, account, debit, credit)', 'provider_event(id, provider, payload, processed)'],
    decisions: [
      { decision: 'Use idempotency for every payment mutation.', why: 'Network retries are common and duplicate charges are unacceptable.', wrongDirection: 'Treat every retry as a new payment.', correction: 'Store idempotency key and replay same result.' },
      { decision: 'Use append-only ledger.', why: 'Money movement needs audit trail and reconciliation.', wrongDirection: 'Only update balance field in place.', correction: 'Record immutable debit/credit entries.' },
      { decision: 'Process webhooks idempotently.', why: 'Providers deliver webhooks multiple times or out of order.', wrongDirection: 'Assume one webhook exactly once.', correction: 'Deduplicate provider event IDs and use state machine transitions.' },
    ],
    scalingNotes: ['Strong consistency for ledger.', 'Async reconciliation.', 'Circuit-break provider failures.', 'Separate authorization from capture where needed.'],
    failureScenarios: [
      { title: 'Webhook delayed', failure: 'Payment status unknown.', recovery: 'Poll provider and reconcile later.' },
      { title: 'Provider timeout', failure: 'Client retries payment.', recovery: 'Idempotency returns original payment status.' },
    ],
    cacheUse: 'Rarely for money state; only cache read-only metadata or risk rules carefully',
  }),
  m({
    slug: 'food-delivery-order-tracking',
    order: 19,
    title: 'Food Delivery Order Tracking',
    difficulty: 'Medium',
    summary: 'Design restaurant order lifecycle, driver assignment, live tracking, notifications, and status consistency.',
    blogIntro: 'Food delivery combines order workflows with real-time location updates and many third-party actors.',
    realWorldContext: 'DoorDash, Swiggy, Zomato, and Uber Eats coordinate customers, restaurants, drivers, payments, and notifications.',
    keyRequirements: ['Place order', 'Restaurant accept/reject', 'Assign driver', 'Track delivery', 'Notify customer', 'Handle cancellation/refund'],
    architecture: ['Customer app', 'Order service', 'Restaurant service', 'Dispatch service', 'Driver location stream', 'Notification service', 'Payment service'],
    dataModel: ['order(id, user_id, restaurant_id, status)', 'order_item(order_id, sku, qty)', 'delivery(order_id, driver_id, status)', 'location(driver_id, lat, lng, updated_at)'],
    decisions: [
      { decision: 'Use state machine for order lifecycle.', why: 'Orders move through controlled states and invalid transitions must be blocked.', wrongDirection: 'Allow any service to set arbitrary status.', correction: 'Define allowed transitions and ownership.' },
      { decision: 'Use events for notifications and downstream updates.', why: 'Status changes need many side effects but should not block core order update.', wrongDirection: 'Call every downstream service synchronously.', correction: 'Emit order events and process asynchronously.' },
      { decision: 'Keep live driver location separate from order DB.', why: 'Location updates are frequent and ephemeral.', wrongDirection: 'Write every driver coordinate into the order row.', correction: 'Use fast latest-location store and archive history separately.' },
    ],
    scalingNotes: ['Partition by city.', 'Use WebSockets for tracking.', 'Use saga for cancellation/refund.', 'Monitor delayed orders.'],
    failureScenarios: [
      { title: 'Restaurant does not respond', failure: 'Order stuck pending.', recovery: 'Timeout and auto-cancel/refund.' },
      { title: 'Driver GPS stale', failure: 'Customer sees wrong location.', recovery: 'Show last-updated time and reassign if heartbeat lost.' },
    ],
    cacheUse: 'For restaurant menus and latest driver location with short TTL',
  }),
  m({
    slug: 'hotel-booking-system',
    order: 20,
    title: 'Hotel Booking System',
    difficulty: 'Medium',
    summary: 'Design search, availability, room inventory, reservation holds, payment, cancellation, and consistency.',
    blogIntro: 'Hotel booking teaches inventory consistency when many users compete for limited rooms across date ranges.',
    realWorldContext: 'Booking.com, Airbnb, Agoda, and Expedia search large inventories while preventing double booking.',
    keyRequirements: ['Search hotels', 'Check availability by date', 'Reserve room', 'Pay booking', 'Cancel/refund', 'Handle price changes'],
    architecture: ['Search API', 'Hotel catalog', 'Availability service', 'Reservation service', 'Payment service', 'Booking DB', 'Search index'],
    dataModel: ['hotel(id, city, amenities)', 'room_inventory(hotel_id, room_type, date, available_count)', 'reservation(id, user_id, room_type, date_range, status)', 'booking(id, reservation_id, payment_status)'],
    decisions: [
      { decision: 'Use search index for discovery, inventory service for truth.', why: 'Search results can be slightly stale; booking availability must be correct.', wrongDirection: 'Trust cached search result as final availability.', correction: 'Revalidate availability during reservation.' },
      { decision: 'Use reservation hold with TTL.', why: 'Payment takes time and inventory must not oversell.', wrongDirection: 'Deduct room only after payment finishes.', correction: 'Hold room count temporarily, then confirm or release.' },
      { decision: 'Model inventory by date.', why: 'Room availability depends on date ranges.', wrongDirection: 'Use one global room count.', correction: 'Track availability per hotel, room type, and date.' },
    ],
    scalingNotes: ['Cache hotel details.', 'Shard by city/region.', 'Precompute availability calendars.', 'Use idempotent booking confirmation.'],
    failureScenarios: [
      { title: 'Stale search result', failure: 'Hotel appears available but sold out.', recovery: 'Show message and suggest alternatives after revalidation.' },
      { title: 'Payment failure', failure: 'Room remains held.', recovery: 'Release hold by TTL and cleanup job.' },
    ],
    cacheUse: 'For hotel details and search results, not final reservation availability',
  }),
  m({
    slug: 'metrics-logging-platform',
    order: 21,
    title: 'Metrics and Logging Platform',
    difficulty: 'Hard',
    summary: 'Design ingestion, buffering, indexing, retention, dashboards, alerts, and high-cardinality control.',
    blogIntro: 'Observability platforms are write-heavy systems that must ingest huge volumes and still answer queries quickly.',
    realWorldContext: 'Datadog, Grafana Cloud, Splunk, and ELK-style platforms collect logs/metrics/traces from production services.',
    keyRequirements: ['Ingest logs/metrics', 'Index searchable fields', 'Query dashboards', 'Trigger alerts', 'Apply retention', 'Control cardinality'],
    architecture: ['Agents', 'Ingestion gateway', 'Kafka/queue', 'Stream processors', 'Time-series/log store', 'Query service', 'Alert engine'],
    dataModel: ['metric(series_key, timestamp, value, tags)', 'log(event_id, timestamp, service, level, message)', 'alert_rule(query, threshold, window)'],
    decisions: [
      { decision: 'Buffer ingestion with Kafka/queue.', why: 'Traffic spikes should not drop observability data immediately.', wrongDirection: 'Write every agent request directly into query database.', correction: 'Use durable ingestion pipeline with backpressure.' },
      { decision: 'Control high-cardinality labels.', why: 'Unbounded labels explode storage and query cost.', wrongDirection: 'Allow user_id/request_id as metric tags everywhere.', correction: 'Limit tags and put high-cardinality data in logs/traces.' },
      { decision: 'Use retention tiers.', why: 'Hot recent data and old archive data have different cost/performance needs.', wrongDirection: 'Keep all raw data forever in hot storage.', correction: 'Downsample/archive older data.' },
    ],
    scalingNotes: ['Partition by time and tenant.', 'Batch writes.', 'Use inverted index for logs.', 'Alert on ingestion lag.'],
    failureScenarios: [
      { title: 'Ingestion spike', failure: 'Agents overwhelm backend.', recovery: 'Buffer, sample, and apply tenant quotas.' },
      { title: 'Query too expensive', failure: 'Dashboard scans huge history.', recovery: 'Use time partitioning, downsampling, and query limits.' },
    ],
    cacheUse: 'For dashboard query results and alert rule metadata, not as event storage',
  }),
  m({
    slug: 'feature-flag-service',
    order: 22,
    title: 'Feature Flag Service',
    difficulty: 'Easy',
    summary: 'Design flag evaluation, targeting rules, rollout percentages, SDK caching, audit logs, and safe fallback.',
    blogIntro: 'Feature flags teach low-latency configuration delivery and safe fallback when control-plane systems fail.',
    realWorldContext: 'LaunchDarkly-style systems let teams roll out features gradually, run experiments, and disable broken features quickly.',
    keyRequirements: ['Create flag', 'Target users/segments', 'Percentage rollout', 'Fast SDK evaluation', 'Audit changes', 'Fallback defaults'],
    architecture: ['Admin UI', 'Flag API', 'Config DB', 'Streaming/polling service', 'SDK cache', 'Audit log'],
    dataModel: ['flag(key, default_value, rules, version)', 'segment(id, rules)', 'audit_event(actor, flag_key, change, timestamp)'],
    decisions: [
      { decision: 'Evaluate flags locally in SDK when possible.', why: 'App request path needs very low latency and high availability.', wrongDirection: 'Call remote flag service on every user request.', correction: 'Stream/poll config to SDK and evaluate locally.' },
      { decision: 'Version and audit every flag change.', why: 'Bad rollout decisions need rollback and accountability.', wrongDirection: 'Overwrite flag config without history.', correction: 'Store versions and audit events.' },
      { decision: 'Define safe fallback values.', why: 'Flag control plane can be unavailable.', wrongDirection: 'Crash app if flag service is down.', correction: 'Use cached config and code-defined defaults.' },
    ],
    scalingNotes: ['Use CDN/streaming for config distribution.', 'Keep evaluation rules simple.', 'Cache segments.', 'Protect admin APIs with strong auth.'],
    failureScenarios: [
      { title: 'Flag service outage', failure: 'Apps cannot fetch latest config.', recovery: 'SDK uses cached config/defaults.' },
      { title: 'Bad rollout', failure: 'New feature breaks production.', recovery: 'Kill switch flag and audit rollback.' },
    ],
    cacheUse: 'For SDK-local flag config and segment rules',
  }),
  m({
    slug: 'live-comments-system',
    order: 23,
    title: 'Live Comments System',
    difficulty: 'Medium',
    summary: 'Design posting, moderation, realtime fanout, pagination, ranking, spam control, and hot live events.',
    blogIntro: 'Live comments combine write bursts, realtime reads, moderation, and product ranking choices.',
    realWorldContext: 'YouTube Live, Twitch, Instagram Live, and sports apps show comments during high-traffic live events.',
    keyRequirements: ['Post comment', 'Show live comments', 'Moderate spam', 'Paginate history', 'Support reactions', 'Handle hot events'],
    architecture: ['Client', 'Comment API', 'Moderation service', 'Comment store', 'Fanout pub/sub', 'WebSocket gateway', 'Ranking/filter service'],
    dataModel: ['comment(id, stream_id, user_id, text, status, created_at)', 'reaction(comment_id, user_id, type)', 'moderation_event(comment_id, reason)'],
    decisions: [
      { decision: 'Use pub/sub for live fanout.', why: 'Many viewers need near-real-time updates.', wrongDirection: 'Make every client poll DB every second.', correction: 'Publish accepted comments to WebSocket/subscription layer.' },
      { decision: 'Moderate before broad fanout.', why: 'Spam can spread instantly in live systems.', wrongDirection: 'Broadcast every comment first and remove later only.', correction: 'Use automated filters and delayed/limited visibility when needed.' },
      { decision: 'Store history separately from live stream buffer.', why: 'Recent live comments and paginated history have different access patterns.', wrongDirection: 'Use only an in-memory buffer.', correction: 'Persist accepted comments and cache recent window.' },
    ],
    scalingNotes: ['Partition by stream_id.', 'Slow-mode/rate-limit hot chats.', 'Cache recent comments.', 'Use moderation queues for review.'],
    failureScenarios: [
      { title: 'Spam flood', failure: 'Live chat becomes unusable.', recovery: 'Enable slow mode, stricter filters, and temporary blocks.' },
      { title: 'WebSocket overload', failure: 'Too many viewers on one event.', recovery: 'Shard fanout by stream and use regional gateways.' },
    ],
    cacheUse: 'For recent live comment window and hot stream metadata',
  }),
  m({
    slug: 'calendar-scheduling-system',
    order: 24,
    title: 'Calendar Scheduling System',
    difficulty: 'Medium',
    summary: 'Design events, invites, availability lookup, reminders, recurring meetings, conflict detection, and time zones.',
    blogIntro: 'Calendar systems teach deceptively hard product correctness: recurrence, time zones, conflicts, and notification timing.',
    realWorldContext: 'Google Calendar, Outlook, Calendly, and booking tools coordinate people across time zones and devices.',
    keyRequirements: ['Create event', 'Invite attendees', 'Check availability', 'Recurring events', 'Reminder notifications', 'Conflict detection'],
    architecture: ['Client', 'Calendar API', 'Event DB', 'Availability service', 'Reminder scheduler', 'Notification service', 'Sync integrations'],
    dataModel: ['event(id, organizer_id, start_at, end_at, timezone, recurrence_rule)', 'attendee(event_id, user_id, status)', 'reminder(event_id, user_id, remind_at)'],
    decisions: [
      { decision: 'Store timestamps carefully with timezone context.', why: 'Recurring meetings and daylight saving changes are tricky.', wrongDirection: 'Store only local formatted time string.', correction: 'Store UTC instants plus timezone/recurrence rules.' },
      { decision: 'Precompute reminders into scheduler queue.', why: 'Reminder delivery needs reliable timing.', wrongDirection: 'Scan all events every minute without indexes.', correction: 'Use indexed remind_at jobs or delayed queue.' },
      { decision: 'Use availability index for busy ranges.', why: 'Finding free slots across many attendees can be expensive.', wrongDirection: 'Load every event forever for every attendee.', correction: 'Query indexed time ranges and cache common availability windows.' },
    ],
    scalingNotes: ['Index by user_id and time range.', 'Handle recurrence expansion carefully.', 'Use idempotent invite notifications.', 'Sync conflicts with external calendars.'],
    failureScenarios: [
      { title: 'Reminder delayed', failure: 'User misses meeting alert.', recovery: 'Monitor scheduler lag and retry notification providers.' },
      { title: 'DST bug', failure: 'Recurring meeting shifts incorrectly.', recovery: 'Use timezone-aware recurrence libraries and tests.' },
    ],
    cacheUse: 'For availability windows and calendar metadata with invalidation on event changes',
  }),
  m({
    slug: 'collaborative-document-editor',
    order: 25,
    title: 'Collaborative Document Editor',
    difficulty: 'Hard',
    summary: 'Design real-time editing, conflict resolution, operation logs, snapshots, presence, permissions, and offline sync.',
    blogIntro: 'Collaborative editors are advanced because many users mutate the same document concurrently while expecting no lost work.',
    realWorldContext: 'Google Docs, Notion, Figma, and Coda use real-time collaboration, permissions, presence, and version history.',
    keyRequirements: ['Edit document together', 'Show presence/cursors', 'Resolve conflicts', 'Save history', 'Support permissions', 'Offline reconnect'],
    architecture: ['Client editor', 'Realtime gateway', 'Collaboration service', 'Operation log', 'Snapshot store', 'Presence store', 'Permission service'],
    dataModel: ['document(id, owner_id, current_snapshot_id)', 'operation(doc_id, seq, user_id, op, timestamp)', 'snapshot(doc_id, version, object_key)', 'presence(doc_id, user_id, cursor, ttl)'],
    decisions: [
      { decision: 'Use OT or CRDT for concurrent edits.', why: 'Multiple users can edit same region at same time.', wrongDirection: 'Last write wins for document body.', correction: 'Use conflict-resolution algorithm and ordered operation log.' },
      { decision: 'Persist operation log and periodic snapshots.', why: 'Snapshots speed load; ops preserve history and recovery.', wrongDirection: 'Only store latest document text.', correction: 'Append ops and compact into snapshots.' },
      { decision: 'Keep presence ephemeral.', why: 'Cursors/online status change often and do not need durable history.', wrongDirection: 'Write every cursor movement to primary DB.', correction: 'Use Redis/WebSocket state with TTL.' },
    ],
    scalingNotes: ['Shard by document_id.', 'Limit active collaborators per session.', 'Use backpressure for operation bursts.', 'Store snapshots in object storage.'],
    failureScenarios: [
      { title: 'Client reconnects offline edits', failure: 'Edits conflict with newer server state.', recovery: 'Transform/merge operations and replay after last acknowledged version.' },
      { title: 'Hot document', failure: 'Thousands edit/view one doc.', recovery: 'Separate viewers from editors and scale fanout gateway.' },
    ],
    cacheUse: 'For presence, recent snapshots, and active document session state',
  }),
];

export function getRealWorldExampleModule(slug: string) {
  return realWorldExampleModules.find((module) => module.slug === slug);
}
